apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: eventhandlers
  name: eventhandlers
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 0
  - name: https
    port: 8080
    targetPort: 0
  selector:
    app: eventhandlers
  type: ClusterIP