apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: researchapi
  name: researchapi
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: researchapi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: researchapi
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: researchapi
        image: '{{ .Values.images.researchapi }}'
        imagePullPolicy: IfNotPresent
        name: researchapi
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
      terminationGracePeriodSeconds: 180