apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: researchapp
  name: researchapp
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 0
  - name: https
    port: 8001
    targetPort: 0
  selector:
    app: researchapp
  type: ClusterIP